### ISSUE TITLE
Successfully acquired the token but the server still returns 401

### ISSUE THREAD

**Issue by lzcapp** [ddoeppner/one-record-server-first-steps#3]
Dear Daniel, thanks for the repo and it helps a lot!

Its just that after we runs the dockers and trying the steps, it stucks at the second step: We successfully retrieved the access token from the Keycloak service, and use it in the "Get ServerInformation" request, but still the server returns "401".

![Snipaste_2024-05-20_18-10-21](https://github.com/ddoeppner/one-record-server-first-steps/assets/12462465/38a5daaf-09bd-4fe4-8689-87d56f966523)

![Snipaste_2024-05-20_18-10-42](https://github.com/ddoeppner/one-record-server-first-steps/assets/12462465/c787f80b-4e25-4f33-af47-15e0adcd7cbe)

Can you please give us some help 🤣! Thank you so much!

**Comment by ddoeppner** [comment]
Hello @lzcapp 
thanks for your comment.

Please be so kind and provide an example access_token from your keycloak or
Check if the "iss" in the JWT token has the same value as configured in the AUTH_VALID_ISSUERS environment variable of the ne-one server.

You can copy the token to https://jwt.io/ and check the "iss" value in the payload. 

For example, 
iss (in the JWT token) = http://localhost:8989/realms/neone

- AUTH_VALID_ISSUERS_LOCAL=http://localhost:8989/realms/neone
- AUTH_ISSUERS_LOCAL_PUBLICKEY_LOCATION=http://keycloak:8989/realms/neone/protocol/openid-connect/certs

If "iss" and AUTH_VALID_ISSUERS_LOCAL are the same, please verify also that the ne-one server container can access the endpoint http://keycloak:8989/realms/neone/protocol/openid-connect/certs.

**Comment by lzcapp** [comment]
@ddoeppner thx!

So based on my understanding, by default the ne-one docker is set to be using the "localhost" `AUTH_VALID_ISSUERS` and therefore we have to request the access token through the "localhost" address of the Keycloak service? And we have to do all the test on the server's local environment?

**Comment by lzcapp** [comment]
@ddoeppner Thanks a lot, with your help now we can finally make some progress. ❤️ 

![Snipaste_2024-05-21_10-06-00](https://github.com/ddoeppner/one-record-server-first-steps/assets/12462465/a8590213-122a-4491-a296-bd6c40620af7)

BTW, one thing we are curious about is that what is the difference between yours neone server and the one from `openlogisticsfoundation`? We tried their neone server (the docker one) at first, and it didn't go well.

**Comment by ddoeppner** [comment]
> So based on my understanding, by default the ne-one docker is set to be using the "localhost" `AUTH_VALID_ISSUERS` and therefore we have to request the access token through the "localhost" address of the Keycloak service? And we have to do all the test on the server's local environment?

You can also work with a remote server, e.g. located at 192.168.178.60

What needs to be changed?
1) Configure ne-one server by either changing
```
- AUTH_VALID_ISSUERS_LOCAL=http://192.168.178.60:8989/realms/neone
- AUTH_ISSUERS_LOCAL_PUBLICKEY_LOCATION=http://keycloak:8989/realms/neone/protocol/openid-connect/certs
```

or adding another trusted issuer by adding the following environment variables
```
- AUTH_VALID_ISSUERS_LOCAL3=http://192.168.178.60:8989/realms/neone
- AUTH_ISSUERS_LOCAL3_PUBLICKEY_LOCATION=http://keycloak:8989/realms/neone/protocol/openid-connect/certs`
```
(This only works if ne-one server and keycloak container are running in the same Docker network, so that ne-one server can access keycloak via its hostname `keycloak`)

2) Get your JWT token from http://192.168.178.60:8989/realms/neone/protocol/openid-connect/token
3) Optional: Copy token into [jwt.io](https://jwt.io/) to verify that is contains `"iss": "http://192.168.178.60:8989/realms/neone"`


<br/><br/><br/><br/>


> BTW, one thing we are curious about is that what is the difference between yours neone server and the one from `openlogisticsfoundation`? We tried their neone server (the docker one) at first, and it didn't go well.

The Open Logistics Foundation (OLF) repository contains the code for the ne-one server. 
This tutorial references and takes this code and some other components (e.g. ne-one play) to provide a starting point and a sample setup that can be used by developers or business analysts for their first steps. 
This tutorial is not intended for use in production and does not provide any tested additional code. 

If you have problems with the ne-one server, please report your problem in the OFL repository, see https://git.openlogisticsfoundation.org/wg-digitalaircargo/ne-one/-/issues

**Comment by lzcapp** [comment]
Dear @ddoeppner , thank you so much for your reponse and helps!
